name: Release RPG Sounds Community Patch

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input tag for release'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'

      - name: Suppress install script
        run: echo "install script suppressor!" > suppress-install-ps1.txt

      - name: Get FMOD library from private repo
        env:
          TOKEN: ${{ secrets.FMOD_LIB_REPO }}
        run: |
          .\github-action-fmod-dl.ps1

          echo "Download successful?" (Test-Path -Path .\fmod_win32_mf\lib\fmod_vc.lib -PathType leaf)

      - name: Build Mod
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/devenv.com" rpgs-patch.sln /Rebuild "Release|x64"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{github.event_name == 'push' && github.ref_name || inputs.tag}}"

          gh release create "$tag" `
            --title="$tag" `
            --draft `
            Info.json .\bin\Release\fmod_win32_mf.dll .\bin\Release\rpgs-patch.dll readme.md license.txt
