name: Release RPG Sounds Community Patch

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - name: Suppress install script
        run: echo "install script suppressor!" > suppress-install-ps1.txt

      - name: Get FMOD library from private repo
        env:
          TOKEN: ${{ secrets.FMOD_LIB_REPO }}
        run: |
          mkdir fmod_win32_mf/lib
          curl --output fmod_win32_mf/lib/fmod_vc.lib -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/pixley/fmod-lib-for-rpgs-patch/main/fmod_vc.lib

      - name: Build Mod
        working-directory:
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/devenv.exe rpgs-patch.sln /Build Release|x64"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            Info.json bin/Release/fmod_win32_mf.dll bin/Release/rpgs-patch.dll readme.md license.txt
